/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router. Do not edit.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as ContactImport } from './routes/contact'
import { Route as CartImport } from './routes/cart'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as AdminSubscribersImport } from './routes/admin/subscribers'
import { Route as AdminSettingsImport } from './routes/admin/settings'
import { Route as AdminPromotionsImport } from './routes/admin/promotions'
import { Route as AdminProductsImport } from './routes/admin/products'
import { Route as AdminOrdersImport } from './routes/admin/orders'
import { Route as AdminMessagesImport } from './routes/admin/messages'
import { Route as AdminInventoryImport } from './routes/admin/inventory'
import { Route as AdminHomepageImport } from './routes/admin/homepage'
import { Route as AdminDashboardImport } from './routes/admin/dashboard'
import { Route as AdminCustomersImport } from './routes/admin/customers'
import { Route as ProductsProductIdImport } from './routes/products.$productId'
import { Route as AdminProductsBulkUploadImport } from './routes/admin/products.bulk-upload'

// Create Virtual Routes

const ShopLazyImport = createFileRoute('/shop')()
const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const CartRoute = CartImport.update({
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ShopLazyRoute = ShopLazyImport.update({
  path: '/shop',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/shop.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const AdminSubscribersRoute = AdminSubscribersImport.update({
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)

const AdminSettingsRoute = AdminSettingsImport.update({
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)

const AdminPromotionsRoute = AdminPromotionsImport.update({
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)

const AdminProductsRoute = AdminProductsImport.update({
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)

const AdminOrdersRoute = AdminOrdersImport.update({
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)

const AdminMessagesRoute = AdminMessagesImport.update({
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)

const AdminInventoryRoute = AdminInventoryImport.update({
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)

const AdminHomepageRoute = AdminHomepageImport.update({
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)

const AdminDashboardRoute = AdminDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

const AdminCustomersRoute = AdminCustomersImport.update({
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)

const ProductsProductIdRoute = ProductsProductIdImport.update({
  path: '/products/$productId',
  getParentRoute: () => rootRoute,
} as any)

const AdminProductsBulkUploadRoute = AdminProductsBulkUploadImport.update({
  path: '/products/bulk-upload',
  getParentRoute: () => AdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/shop': {
      preLoaderRoute: typeof ShopLazyImport
      parentRoute: typeof rootRoute
    }
    '/products/$productId': {
      preLoaderRoute: typeof ProductsProductIdImport
      parentRoute: typeof rootRoute
    }
    '/admin/customers': {
      preLoaderRoute: typeof AdminCustomersImport
      parentRoute: typeof AdminImport
    }
    '/admin/dashboard': {
      preLoaderRoute: typeof AdminDashboardImport
      parentRoute: typeof AdminImport
    }
    '/admin/homepage': {
      preLoaderRoute: typeof AdminHomepageImport
      parentRoute: typeof AdminImport
    }
    '/admin/inventory': {
      preLoaderRoute: typeof AdminInventoryImport
      parentRoute: typeof AdminImport
    }
    '/admin/messages': {
      preLoaderRoute: typeof AdminMessagesImport
      parentRoute: typeof AdminImport
    }
    '/admin/orders': {
      preLoaderRoute: typeof AdminOrdersImport
      parentRoute: typeof AdminImport
    }
    '/admin/products': {
      preLoaderRoute: typeof AdminProductsImport
      parentRoute: typeof AdminImport
    }
    '/admin/promotions': {
      preLoaderRoute: typeof AdminPromotionsImport
      parentRoute: typeof AdminImport
    }
    '/admin/settings': {
      preLoaderRoute: typeof AdminSettingsImport
      parentRoute: typeof AdminImport
    }
    '/admin/subscribers': {
      preLoaderRoute: typeof AdminSubscribersImport
      parentRoute: typeof AdminImport
    }
    '/admin/products/bulk-upload': {
      preLoaderRoute: typeof AdminProductsBulkUploadImport
      parentRoute: typeof AdminImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AdminRoute.addChildren([
    AdminCustomersRoute,
    AdminDashboardRoute,
    AdminHomepageRoute,
    AdminInventoryRoute,
    AdminMessagesRoute,
    AdminOrdersRoute,
    AdminProductsRoute,
    AdminPromotionsRoute,
    AdminSettingsRoute,
    AdminSubscribersRoute,
    AdminProductsBulkUploadRoute,
  ]),
  CartRoute,
  ContactRoute,
  LoginRoute,
  AboutLazyRoute,
  ShopLazyRoute,
  ProductsProductIdRoute,
])

/* prettier-ignore-end */
